# -*- coding: utf-8 -*-
"""session 3 NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZeTM_fCPU0w22Q9wl-M4ow5e4SvFijA

#part of speech (POS)
"""

import spacy
!python -m spacy download en_core_web_sm #pre trained model
#POS , NER , Dependency parsing

"""#POS using spacy"""

nlp = spacy.load('en_core_web_sm')
doc = nlp('Elon flew to mars yesterday . He carried biryani masala with him')
for token in doc :
  print(token, "||" ,token.pos_ , '||' ,spacy.explain(token.pos_ ))

earnings_text="""Microsoft Corp. today announced the following results for the quarter ended December 31, 2021, as compared to the corresponding
.Revenue was $51.7 billion and increased 20%
.Operating income was $22.2 billion and increased 24%
.Net income was $18.8 billion and increased 21%
"Diluted earnings per share was $2.48 and increased 22%
"Digital technology is the most malleable resource at the world's disposal to overcome constraints and reimagine everyday work and life," said S
"Solid commercial execution, represented by strong bookings growth driven by long-term Azure commitments, increased Microsoft Cloud revenue to $"""


# delete >>>pos [SPACE, PUNCT, X]
nlp = spacy.load('en_core_web_sm')
doc = nlp(earnings_text)

filtered_tokens = []
for token in doc:
  if token.pos not in ["SPACE" , "PUNCT" , "X"]:
    filtered_tokens.append(token)

filtered_tokens[:10]

count = doc.count_by(spacy.attrs.POS)
count

doc.vocab[96].text

count.items()

for i,v in count.items():
  print(doc.vocab[i].text , "|" , v)

"""#POS using nltk"""

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

text = "The quick brown fox jumps over the lazy dog"
words = nltk.word_tokenize(text)
words

pos_tags = nltk.pos_tag(words)
pos_tags



